// ============================================================================
// WalkableGrid.js — where on the floor plan a person can be
//
// Built from the GREEN area of the floor-plan image (floorplanWalkable.js,
// generated by scripts/build_walkable_grid.py). Gray (cabins, furniture),
// walls and everything outside the plan are not walkable.
//
// Used everywhere a position is produced, so the dot and the walked path stay
// on the green:
//   - ParticleFilter: a step that crosses gray is impossible;
//   - FusionEngine: any estimate that lands on gray (EKF, start fix, a cloud
//     average at a corner) is moved to the nearest green point;
//   - InitialPositionSolver: a start candidate inside a cabin is rejected,
//     which also settles most mirror ambiguities on its own.
//
// The grid covers the whole room as FRACTIONS of its size, exactly like the
// image (which is stretched over the room), so it keeps lining up if the room
// size is changed. Units: feet, y up (0 at the bottom of the plan).
// ============================================================================

import { FLOORPLAN_WALKABLE } from "./floorplanWalkable.js";

const B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

function decodeBase64(s) {
  const out = [];
  let buf = 0, bits = 0;
  for (const ch of s) {
    if (ch === "=") break;
    const v = B64.indexOf(ch);
    if (v < 0) continue;
    buf = (buf << 6) | v;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out.push((buf >> bits) & 0xff);
    }
  }
  return out;
}

export class WalkableGrid {
  constructor(data = FLOORPLAN_WALKABLE) {
    this.cols = data.cols;
    this.rows = data.rows;
    const bytes = decodeBase64(data.bits);
    this.cells = new Uint8Array(this.cols * this.rows);
    for (let i = 0; i < this.cells.length; i++) this.cells[i] = (bytes[i >> 3] >> (i & 7)) & 1;
    this.setRoom(72, 72);
    this._nearestCache = new Map();
  }

  setRoom(widthFt, heightFt) {
    this.w = widthFt > 0 ? widthFt : 72;
    this.h = heightFt > 0 ? heightFt : 72;
    this.cw = this.w / this.cols;
    this.ch = this.h / this.rows;
    this._nearestCache = new Map();
  }

  _cell(x, y) {
    if (!(x >= 0 && y >= 0 && x < this.w && y < this.h)) return -1;
    const c = Math.min(this.cols - 1, Math.floor(x / this.cw));
    const r = Math.min(this.rows - 1, Math.floor(y / this.ch));
    return r * this.cols + c;
  }

  /** On the green, inside the plan. */
  isWalkable(x, y) {
    const i = this._cell(x, y);
    return i >= 0 && this.cells[i] === 1;
  }

  /** Every point of the straight line from (x0,y0) to (x1,y1) is on the green. */
  segmentWalkable(x0, y0, x1, y1) {
    const len = Math.hypot(x1 - x0, y1 - y0);
    const n = Math.max(1, Math.ceil(len / (0.5 * Math.min(this.cw, this.ch))));
    for (let k = 0; k <= n; k++) {
      const f = k / n;
      if (!this.isWalkable(x0 + f * (x1 - x0), y0 + f * (y1 - y0))) return false;
    }
    return true;
  }

  /**
   * Nearest point on the green (centre of the nearest walkable cell), and how
   * far it is (ft). A point already on the green is returned unchanged.
   */
  nearest(p, maxFt = 30) {
    const x = p?.x, y = p?.y;
    if (!Number.isFinite(x) || !Number.isFinite(y)) return null;
    if (this.isWalkable(x, y)) return { x, y, distFt: 0 };
    const key = `${Math.round(x * 4)}:${Math.round(y * 4)}`;
    const hit = this._nearestCache.get(key);
    if (hit) return hit;
    const c0 = Math.floor(x / this.cw), r0 = Math.floor(y / this.ch);
    const maxRing = Math.ceil(maxFt / Math.min(this.cw, this.ch));
    let best = null;
    for (let ring = 0; ring <= maxRing; ring++) {
      for (let dr = -ring; dr <= ring; dr++) {
        for (let dc = -ring; dc <= ring; dc++) {
          if (Math.max(Math.abs(dr), Math.abs(dc)) !== ring) continue;
          const r = r0 + dr, c = c0 + dc;
          if (r < 0 || c < 0 || r >= this.rows || c >= this.cols) continue;
          if (!this.cells[r * this.cols + c]) continue;
          const cx = (c + 0.5) * this.cw, cy = (r + 0.5) * this.ch;
          const d = Math.hypot(cx - x, cy - y);
          if (!best || d < best.distFt) best = { x: cx, y: cy, distFt: d };
        }
      }
      // Anything in a later ring is at least ring * cell away.
      if (best && best.distFt <= ring * Math.min(this.cw, this.ch)) break;
    }
    if (this._nearestCache.size > 5000) this._nearestCache.clear();
    if (best) this._nearestCache.set(key, best);
    return best;
  }
}

/** The office floor plan's walkable area. */
export const floorplanGrid = new WalkableGrid();
