"""
Builds services/floorplanWalkable.js from the floor-plan image.

The walkable area is the GREEN part of assets/floorplans/office-72x72.png
(gray = cabins / furniture, dark = walls). The image is drawn stretched over
the whole room on the Fusion Map, so a pixel at (px, py) is the point
x = px / W * room width, y = room height - py / H * room height. Cells are a
fraction of the room (not fixed feet), so the grid keeps lining up with the
image if the room size is changed in the app.

Run again whenever the floor plan image changes:
    python scripts/build_walkable_grid.py
Needs Pillow (pip install pillow).
"""
import base64, os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "floorplans", "office-72x72.png")
OUT = os.path.join(ROOT, "services", "floorplanWalkable.js")
COLS = ROWS = 144          # 0.5 ft cells for a 72 x 72 ft room
MIN_GREEN_SHARE = 0.5      # a cell is walkable if at least half of it is green


def is_green(r, g, b):
    return g >= 180 and g - r >= 15 and g - b >= 15


def main():
    im = Image.open(SRC).convert("RGB")
    W, H = im.size
    px = im.load()
    green = [[is_green(*px[x, y]) for x in range(W)] for y in range(H)]
    # cell (c, r): r = 0 is the BOTTOM row (y = 0), as in the app's coordinates
    cells = []
    for r in range(ROWS):
        y0 = int((ROWS - 1 - r) / ROWS * H); y1 = max(y0 + 1, int((ROWS - r) / ROWS * H))
        row = []
        for c in range(COLS):
            x0 = int(c / COLS * W); x1 = max(x0 + 1, int((c + 1) / COLS * W))
            n = g = 0
            for yy in range(y0, y1):
                for xx in range(x0, x1):
                    n += 1; g += green[yy][xx]
            row.append(g / n >= MIN_GREEN_SHARE)
        cells.append(row)
    # Clean-up: fill 1-cell holes inside the green (door arcs, text), drop
    # isolated green specks.
    def nb(r, c):
        return [cells[rr][cc] for rr, cc in ((r - 1, c), (r + 1, c), (r, c - 1), (r, c + 1))
                if 0 <= rr < ROWS and 0 <= cc < COLS]
    for _ in range(2):
        nxt = [row[:] for row in cells]
        for r in range(ROWS):
            for c in range(COLS):
                k = sum(nb(r, c))
                if not cells[r][c] and k >= 3: nxt[r][c] = True
                if cells[r][c] and k <= 1: nxt[r][c] = False
        cells = nxt
    bits = bytearray((ROWS * COLS + 7) // 8)
    for r in range(ROWS):
        for c in range(COLS):
            if cells[r][c]:
                i = r * COLS + c
                bits[i >> 3] |= 1 << (i & 7)
    b64 = base64.b64encode(bytes(bits)).decode()
    walk = sum(map(sum, cells))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// GENERATED by scripts/build_walkable_grid.py from\n")
        f.write("// assets/floorplans/office-72x72.png - do not edit by hand.\n")
        f.write("// Walkable (green) cells of the floor plan; see WalkableGrid.js.\n")
        f.write(f"export const FLOORPLAN_WALKABLE = {{ cols: {COLS}, rows: {ROWS}, bits: \"{b64}\" }};\n")
    print(f"wrote {OUT}: {walk}/{ROWS*COLS} cells walkable ({100*walk/(ROWS*COLS):.0f}%)")
    # Preview for checking: walkable cells tinted blue over the plan.
    prev = im.copy().resize((W * 2, H * 2))
    pp = prev.load()
    for r in range(ROWS):
        for c in range(COLS):
            if cells[r][c]:
                x0 = int(c / COLS * W * 2); x1 = int((c + 1) / COLS * W * 2)
                y0 = int((ROWS - 1 - r) / ROWS * H * 2); y1 = int((ROWS - r) / ROWS * H * 2)
                for yy in range(y0, y1):
                    for xx in range(x0, x1):
                        R, G, B = pp[xx, yy]; pp[xx, yy] = (R // 3, G // 2, min(255, B // 2 + 130))
    out = sys.argv[1] if len(sys.argv) > 1 else None
    if out: prev.save(out); print("preview", out)


if __name__ == "__main__":
    main()
